name: infra-apply

on:
  push:
    branches:
      - demo-argocd
    paths:
      - 'gitops/terraform/**'
      - '.github/workflows/**'

env:
  AWS_REGION: "us-east-2"

jobs:
  apply-appstack:
    permissions:
      contents: write
      id-token: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ${{ env.AWS_REGION }}
          role-to-assume: ${{ vars.AWS_ROLE_TO_ASSUME }}

      - name: Apply TF Changes
        uses: ./.github/workflows/apply
        with:
          tf_state_bucket: ${{ vars.TF_STATE_BUCKET }}
          tf_state_key: ${{ github.repository }}/terraform.tfstate
          aws_region: ${{ env.AWS_REGION }}
